attributes:
  multibackend:
    value: false
    label: 'Multibackend enabled'
    description: 'Eqlx driver will be used as a Cinder Multibackend feature'
    weight: 35
    type: "checkbox"
  san_ip:
    value: ''
    label: 'IP' 
    description: 'The IP address of the Dell EqualLogic array.'
    weight: 25
    type: "text"
  san_login:
    value: ''
    label: 'Username'
    description: 'The account to use for issuing SSH commands.'
    weight: 45
    type: "text"
  san_password:
    value: ''
    label: 'Password'
    description: 'The password for the specified SSH account.'
    weight: 45
    type: "password"
  volume_backend_name:
    value: ''
    label: 'Backend Name'
    description: 'Volume Backend Name'
    weight: 45
    type: "text"
  eqlx_group_name:
    value: ''
    label: 'Volume Group Name'
    description: 'Volume GroupName, The CLI prompt message without >.'
    weight: 45
    type: "text"
  eqlx_pool:
    value: ''
    label: 'Pool Name'
    description: 'The pool in which volumes will be created.'
    weight: 45
    type: "text"
